### ISSUE TITLE
Bug: Killing ships doesn't award points

### ISSUE THREAD

**Issue by ashavit** [yuri1992/battleShips#20]

**Comment by yuri1992** [comment]
Currently I do not counting score, the score affected only by the amount of "hits"
You can print playerStatistic.getHits().size() as the score

**Comment by ashavit** [comment]
Each ship has a score configured in xml. we need to add points when the ship is sunk.
I was thinking to add a hits member to ship class, and a bool isKilled if hits==size.
And on player turn, after a hit - check if ship is dead and add points.

**Comment by yuri1992** [comment]
you have `isDrowned` method on each ship, that return true when ship was "killed"
