### ISSUE TITLE
MatchHub - messages are displayed one under another

### ISSUE THREAD

**Issue by ashavit** [yuri1992/battleShips#56]
MatchHub - if had several messages they are not replaced but displayed under the prev on (see screen shot)

**Comment by ashavit** [comment]
<img width="746" alt="screen shot 2017-10-22 at 8 12 32 am" src="https://user-images.githubusercontent.com/6129781/31863656-21b4d672-b759-11e7-9955-6165d0e3503c.png">

**Comment by yuri1992** [comment]
Done.
