### ISSUE TITLE
User logs out should exit all tabs

### ISSUE THREAD

**Issue by ashavit** [yuri1992/battleShips#66]
1. Log in with a user, see the hub screen
2. Open another tab, see the hub screen
3. log out from one of the tabs ==> the other tab shows error loading data

==> should exit to login screen

יש לאפשר למשתמש לבצע Logout מהמערכת ע"י כפתור ייעודי. במידה וביצע Logout הוא נמחק מרישומי המערכת ויכול לבצע רישום מחדש (גם באותו השם). במידה וקיימים כמה browser-ים שונים שמהם מחובר המשתמש, הרי שהחל מעכשיו הוא כבר לא קיים יותר במערכת ולכן הוא יתנתק ממנה גם בכל שאר ה- browser-ים.

**Comment by yuri1992** [comment]
Done
